version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: develop
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: develop
    schedule:
      interval: 'monthly'
